import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './header'
import Footer from './footer/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const navLinks = [
  { title: 'Home', href: '/' },
  { title: 'Contacts', href: '/contacts' },
  { title: 'About', href: '/about' },
  { title: 'Blog', href: '/blog' },
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="h-full" lang="en">
      <body className={`${inter.className} h-full`}>
        <div className="min-h-full flex flex-col">
          <Header navLinks={navLinks} />
          <main className="mx-auto w-5/6 flex-auto">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
